### ISSUE TITLE
Leader Fields

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/Keystone#22]
In developing the Community Group and Ministry Team portions, we noticed some interesting aspects of the database that will need some changes made. We need to at least know the answer for what fields should be used so that we can link the redesigned Ministry Team and Community Group portions of the app to the right fields.

Problem 1) The Ministry Team Leader fields exist in both the Users section and the Ministry Teams section, but one does not update when the other is changed. Further, when trying to save in the Users section, there is a data validation error when attempting to put a Ministry Team with the User. Solving this could mean either removing the Ministry Team Leader option from the Users section OR linking the two together so that the Users and Ministry Team sections are consistent regardless of where you update it from. 

Problem 2) The Community Group Leader field exists only in the Community Group section. If the choice is made to link the Ministry Team Leader sections together (from Problem 1), then the Community Group Leader field should also exist within the User section so that the database matches for the two types of leaders. If not linking together, then no changes are required for Community Group Leaders.

**Comment by fedorareis** [comment]
@kyle-fletcher, So the way it is currently set up the Ministry Teams section in the User profile is Ministry teams that the user is involved with and wants notifications for. We could change that or add a Ministry Team Leader section if we wanted but that is how it currently works.

Also, the validation error you were receiving was due to data in a different field not being in the format it should be in. The data (in this case a phone number) was entered before we enforced the format of the data entered.

**Comment by fedorareis** [comment]
I am looking into this further. https://gist.github.com/JedWatson/8519978 might hold some answers. I'm not 100% convinced that 2-way relationships work but we will see.

That, however, means this is going to fall on our more long-term roadmap.
